title: Kyle Schaeffer
description: "Develop, design, interact, educate."
email: kyle@spirito.us
baseurl: ""
url: "https://kyleschaeffer.com"
twitter_username: kyleschaeffer
github_username: kyleschaeffer
paginate: 10
paginate_path: "/:num/"

permalink: pretty
markdown: kramdown
sass:
  sass_dir: sass
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
