title: Kyle Schaeffer
description: Web Design and SharePoint Branding
email: kyle@spirito.us
baseurl: ""
url: "https://kyleschaeffer.com"
twitter_username: kyleschaeffer
github_username:  kyleschaeffer

permalink: pretty
markdown: kramdown
sass:
  sass_dir: sass
  style: compressed
plugins:
  - jekyll-feed
